// src/constants/carBrands.ts

import rawBrandsWithId from './carBrandsWithId.json'

export interface CarBrand {
  id: string;
  name: string;
  firstLetter: string;
  logoUrl?: string;
}

// 辅助函数：生成 slug（与下载脚本中的 generateSlug 保持一致）
const slugify = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/[·・•\-_\s]+/g, '-')
    .replace(/[^\w\u4e00-\u9fa5\-]+/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
};

// 辅助函数：获取首字母
const getFirstLetter = (name: string): string => {
  const first = name.charAt(0);
  if (/[A-Za-z]/.test(first)) return first.toUpperCase();
  if (/[0-9]/.test(first)) return '#';
  return '#';
};

// 原始品牌列表（假设你已经有 rawBrands 数组，里面只有 name）
const rawBrands: { name: string }[] = [
  { name: '阿尔法-罗密欧'},
  { name: '奥迪AUDI' },
  { name: 'alpina' },

  // B 组
  { name: 'BAC' },
  { name: 'BAO' },
  { name: 'Bertone' },
  { name: 'BeyonCa' },
  { name: 'Bizzarrini' },
  { name: 'Bollinger Motors' },
  { name: 'Bovensiepen' },
  { name: 'Bowler' },
  { name: '北汽昌河' },
  { name: '北汽道达' },
  { name: '北汽幻速' },
  { name: '北汽瑞翔' },
  { name: '北汽泰普' },
  { name: '北汽威旺' },
  { name: '北汽新能源' },
  { name: '北京汽车' },
  { name: '北京汽车制造厂' },
  { name: '北京清行' },
  { name: '北京越野' },
  { name: '北方房车' },
  { name: '保斐利' },
  { name: '保时捷' },
  { name: '宝马' },
  { name: '宝骏' },
  { name: '宝骐汽车' },
  { name: '宝腾' },
  { name: '宝沃' },
  { name: '百智新能源' },
  { name: '佰斯威' },
  { name: '拜腾' },
  { name: '奔腾' },
  { name: '比亚迪' },
  { name: '比德文汽车' },
  { name: '比克汽车' },
  { name: '比速汽车' },
  { name: '标致' },
  { name: '别克' },
  { name: '宾利' },
  { name: '宾尼法利纳' },
  { name: '布加迪' },
  { name: '巴菲特汽车' },
  { name: '梅赛德斯-奔驰' },

  // C 组
  { name: 'CEER' },
  { name: 'Canoo' },
  { name: 'Caterham' },
  { name: 'Conquest' },
  { name: 'Continental' },
  { name: 'Corbellati' },
  { name: 'Cupra' },
  { name: 'Czinger' },
  { name: '长江EV' },
  { name: '昶洧' },
  { name: '曹操汽车' },
  { name: '车驰汽车' },
  { name: '超境汽车' },
  { name: '成功汽车' },
  { name: '创维汽车' },
  { name: '长安' },
  { name: '长安凯程' },
  { name: '长安启源' },
  { name: '长安欧尚' },
  { name: '长安跨越' },

  // D 组
  { name: 'E-Legend' },
  { name: 'EdisonFuture' },
  { name: 'Electra Meccanica' },
  { name: 'Elektron' },
  { name: 'Elemental' },
  { name: 'e.GO' },
  { name: '大驰房车' },
  { name: '大发' },
  { name: '大众' },
  { name: '戴姆勒' },
  { name: '道奇' },
  { name: '道朗格' },
  { name: '东南' },
  { name: '东风' },
  { name: '东风奕派' },

  // E 组（实际是 F？原文本 F 组）
  { name: 'FM Auto' },
  { name: 'FOX Automotive' },
  { name: 'Faraday Future' },
  { name: 'Faraday X' },
  { name: 'Fisker' },
  { name: 'Foxtron' },
  { name: 'Frangivento' },
  { name: 'Fresco' },
  { name: '法拉利' },
  { name: '法诺新能源' },
  { name: '方程豹' },
  { name: '飞碟汽车' },
  { name: '福特' },
  { name: '福田' },
  { name: '福迪' },
  { name: '富古汽车' },

  // G 组
  { name: 'G&B Design' },
  { name: 'G-Power' },
  { name: 'GAZ' },
  { name: 'GFG Style' },
  { name: 'GLM' },
  { name: 'GMA' },
  { name: 'GMC' },
  { name: 'GTA' },
  { name: 'GUNTHER WERKS' },
  { name: 'GYON' },
  { name: 'Gemballa' },
  { name: 'Giamaro' },
  { name: 'Ginetta' },
  { name: 'Gumpert' },
  { name: '广汽传祺' },
  { name: '广汽吉奥' },
  { name: '广汽昊铂' },
  { name: '广汽集团' },
  { name: '广通客车' },
  { name: '格罗夫' },
  { name: '观致' },
  { name: '国吉商用车' },
  { name: '国机智骏' },
  { name: '国金汽车' },

  // H 组
  { name: 'HOFELE' },
  { name: 'Hennessey' },
  { name: 'Hispano Suiza' },
  { name: 'Hopium' },
  { name: 'Hudson' },
  { name: 'Hyperion' },
  { name: '哈弗' },
  { name: '海马' },
  { name: '海格' },
  { name: '汉龙汽车' },
  { name: '汉腾汽车' },
  { name: '悍马' },
  { name: '合创汽车' },
  { name: '红旗' },
  { name: '红星汽车' },
  { name: '宏远汽车' },
  { name: '华东汽车' },
  { name: '华人运通' },
  { name: '华凯' },
  { name: '华利' },
  { name: '华境' },
  { name: '华晨新日' },
  { name: '华普' },
  { name: '华梓汽车' },
  { name: '华泰' },
  { name: '华泰新能源' },
  { name: '华颂' },
  { name: '华骐' },
  { name: '恒驰' },
  { name: '恒天' },
  { name: '恒信致远' },
  { name: '恒润汽车' },
  { name: '鸿日' },
  { name: '小虎' },
  { name: '货拉拉多拉汽车' },
  { name: '皓旅房车' },
  { name: '赫菲特汽车' },

  // I 组
  { name: 'IED' },
  { name: 'IMSA英飒' },
  { name: 'INDI' },
  { name: 'INKAS' },
  { name: 'IZERA' },
  { name: 'Icona' },
  { name: 'Inferno' },
  { name: 'Italdesign' },
  { name: 'iCAR' },
  { name: 'nanoFLOWCELL' },

  // J 组
  { name: 'Jannarelly' },
  { name: 'Jeep' },
  { name: '吉利几何' },
  { name: '吉利汽车' },
  { name: '吉利银河' },
  { name: '吉利雷达' },
  { name: '吉祥汽车' },
  { name: '捷达' },
  { name: '捷豹' },
  { name: '捷尼赛思' },
  { name: '捷途' },
  { name: '捷途山海' },
  { name: '金杯' },
  { name: '金杯新能源' },
  { name: '金冠汽车' },
  { name: '金琥新能源' },
  { name: '金旅' },
  { name: '金龙' },
  { name: '金龙礼宾' },
  { name: '君马汽车' },
  { name: '江南汽车' },
  { name: '江汽集团' },
  { name: '江淮汽车' },
  { name: '江淮瑞风' },
  { name: '江淮钇为' },
  { name: '江铃' },
  { name: '江铃晶马汽车' },
  { name: '江铃集团房车' },
  { name: '江铃集团新能源' },
  { name: '钧天' },
  { name: '景飞汽车' },
  { name: '骏驰' },

  // K 组
  { name: 'KALMAR' },
  { name: 'KHANN' },
  { name: 'KTM' },
  { name: 'Karlmann King' },
  { name: 'Karma' },
  { name: 'Kimera' },
  { name: '开瑞' },
  { name: '开沃汽车' },
  { name: '开利' },
  { name: '凯佰赫' },
  { name: '卡尔森' },
  { name: '凯马' },
  { name: '凯翼' },
  { name: '凯翼汽车' },
  { name: '凯迪拉克' },
  { name: '坎帕' },
  { name: '科尼赛克' },
  { name: '克莱斯勒' },
  { name: '克蒂汽车' },
  { name: '克慕勒' },
  { name: '魁士' },
  { name: '卡升' },
  { name: '卡威' },
  { name: '卡文汽车' },
  { name: '卡驰汽车' },
  { name: '焜驰' },

  // L 组
  { name: 'LEVC' },
  { name: 'LIMGENE凌际' },
  { name: 'LITE' },
  { name: 'LIUX' },
  { name: 'LOCAL MOTORS' },
  { name: 'LUMMA' },
  { name: 'LeSEE' },
  { name: 'Lightyear' },
  { name: 'Lordstown Motors' },
  { name: 'Lorinser罗伦士' },
  { name: 'Lucid' },
  { name: '蓝电' },
  { name: '蓝旗亚' },
  { name: '蓝擎汽车' },
  { name: '猎豹汽车' },
  { name: '乐道' },
  { name: '雷驰汽车' },
  { name: '雷丁' },
  { name: '雷诺' },
  { name: '雷诺三星' },
  { name: '雷克萨斯' },
  { name: '零跑汽车' },
  { name: '领克' },
  { name: '领汇' },
  { name: '领途汽车' },
  { name: '领志' },
  { name: '林肯' },
  { name: '铃木' },
  { name: '陆地方舟' },
  { name: '陆风' },
  { name: '路虎' },
  { name: '罗夫哈特' },
  { name: '莱茵汽车' },
  { name: '岚图汽车' },
  { name: '览众房车' },
  { name: '莲花汽车' },
  { name: '莲花跑车' },
  { name: '凌宝汽车' },
  { name: '灵悉' },
  { name: '理想' },
  { name: '菱势汽车' },
  { name: '龙程汽车' },
  { name: '珑致' },

  // M 组
  { name: 'MAGNA' },
  { name: 'MELKUS' },
  { name: 'MILITEM' },
  { name: 'MINI' },
  { name: 'Mahindra' },
  { name: 'Manhart' },
  { name: 'Mazzanti' },
  { name: 'Meyers Manx' },
  { name: 'Micro' },
  { name: 'Mobilize' },
  { name: 'Moke' },
  { name: 'Mole' },
  { name: 'Mullen' },
  { name: 'Munro' },
  { name: '玛莎拉蒂' },
  { name: '迈凯伦' },
  { name: '迈巴赫' },
  { name: '迈迈' },
  { name: '迈莎锐' },
  { name: '迈越' },
  { name: '猛士' },
  { name: '马自达' },
  { name: '摩根' },
  { name: '摩登汽车' },
  { name: '敏安汽车' },
  { name: '名爵' },

  // N 组
  { name: 'NEVS国能汽车' },
  { name: 'NEXT LEVEL' },
  { name: 'NamX' },
  { name: 'Neuron EV' },
  { name: 'Nikola' },
  { name: 'Noble' },
  { name: 'Novitec' },
  { name: '哪吒汽车' },
  { name: '纳智捷' },

  // O 组
  { name: '欧宝' },
  { name: '欧拉' },
  { name: '欧朗' },
  { name: '欧联' },
  { name: '欧铃汽车' },
  { name: '讴歌' },
  { name: '诺马迪森房车' },

  // P 组
  { name: 'Piëch Automotive' },
  { name: 'Pogea Racing' },
  { name: 'Polestar极星' },
  { name: 'Posaidon' },
  { name: 'Praga' },
  { name: 'Puritalia' },
  { name: '帕加尼' },
  { name: '朋克汽车' },
  { name: '佩奇奥' },
  { name: '普曼·巅峰' },

  // Q 组
  { name: '奇瑞' },
  { name: '奇瑞QQ' },
  { name: '奇瑞新能源' },
  { name: '奇瑞风云' },
  { name: '奇鲁汽车' },
  { name: '启境' },
  { name: '启辰' },
  { name: '前途' },
  { name: '庆铃汽车' },
  { name: '清源汽车' },
  { name: '轻橙时代' },
  { name: '骐蔚汽车' },
  { name: '骐铃汽车' },
  { name: '起亚' },
  { name: '乔治·巴顿' },
  { name: '全球鹰' },

  // R 组
  { name: 'RAM' },
  { name: 'RENOVO' },
  { name: 'RIVIAN' },
  { name: 'ROX极石' },
  { name: 'Radford' },
  { name: 'Radical' },
  { name: 'Red Bull' },
  { name: 'Revo Zero' },
  { name: 'Rezvani' },
  { name: 'Rinspeed' },
  { name: '日产' },
  { name: '荣威' },
  { name: '如虎' },
  { name: '瑞驰汽车' },
  { name: '瑞弗房车' },
  { name: '瑞麒' },
  { name: '瑞腾汽车' },
  { name: '瑞一汽车' },
  { name: '睿蓝汽车' },

  // S 组
  { name: 'SERES赛力斯' },
  { name: 'SHELBY' },
  { name: 'SIN CARS' },
  { name: 'SONGSAN MOTORS' },
  { name: 'SONY' },
  { name: 'SPIRRA' },
  { name: 'SSC' },
  { name: 'STI' },
  { name: 'SWM斯威汽车' },
  { name: 'Santana' },
  { name: 'Scion' },
  { name: 'Scout' },
  { name: 'Share2Drive' },
  { name: 'Sono Motors' },
  { name: 'Spofec' },
  { name: 'Spyros Panopoulos' },
  { name: 'smart' },
  { name: '萨博' },
  { name: '三菱' },
  { name: '申龙汽车' },
  { name: '深蓝汽车' },
  { name: '上喆' },
  { name: '上汽跃进' },
  { name: '上汽集团' },
  { name: '上海' },
  { name: '世极' },
  { name: '世爵' },
  { name: '首望' },
  { name: '陕汽通家' },
  { name: '思皓' },
  { name: '思铭' },
  { name: '斯巴鲁' },
  { name: '斯达泰克' },
  { name: '斯柯达' },
  { name: '斯太尔' },
  { name: '双环' },
  { name: '双龙' },
  { name: '神州' },
  { name: '盛唐' },
  { name: '速达' },
  { name: '索纳塔' },
  { name: '尚界' },
  { name: '示界' },

  // T 组
  { name: 'TECHART' },
  { name: 'TOGG' },
  { name: 'TOROIDION' },
  { name: 'TVR' },
  { name: 'Theon Design' },
  { name: 'TopCar' },
  { name: 'Touring Superleggera' },
  { name: 'Tramontana' },
  { name: 'Triton' },
  { name: 'Troller' },
  { name: '塔塔' },
  { name: '坦克' },
  { name: '泰克鲁斯·腾风' },
  { name: '腾势' },
  { name: '天际汽车' },
  { name: '特斯拉' },
  { name: '途柚汽车' },
  { name: '拓锐斯特' },

  // U 组
  { name: 'Ultima' },

  // V 组
  { name: 'VANTAS' },
  { name: 'VIRITECH' },
  { name: 'VLF Automotive' },
  { name: 'Vanda Electric' },
  { name: 'Vega Innovations' },
  { name: 'Venturi' },
  { name: 'Vinfast' },
  { name: '沃尔沃' },
  { name: '威兹曼' },
  { name: '威马汽车' },
  { name: '威麟' },
  { name: '潍柴英致' },
  { name: '魏牌' },
  { name: '未奥汽车' },
  { name: '瓦滋' },
  { name: '维努斯' },
  { name: '沃克斯豪尔' },
  { name: '沃勒汽车' },
  { name: '沃森威尔' },
  { name: '蔚来' },
  { name: '远程' },
  { name: '远航汽车' },
  { name: '越界' },
  { name: '运良汽车' },
  { name: '翼刻' },
  { name: '英菲尼迪' },
  { name: '英力士掷弹兵' },
  { name: '悠宝利' },
  { name: '悠跑科技' },
  { name: '予风汽车' },
  { name: '御捷' },
  { name: '游侠' },
  { name: '裕路' },
  { name: '驭胜' },
  { name: '元征' },
  { name: '云度' },
  { name: '云雀汽车' },
  { name: '银隆新能源' },
  { name: '雅升汽车' },
  { name: '一汽' },
  { name: '一汽凌河' },
  { name: '依维柯' },
  { name: '永源' },
  { name: '宇通客车' },
  { name: '宇通房车' },
  { name: 'firefly萤火虫' },
  { name: '烨' },
  { name: '霞客乐房车' },

  // W 组
  { name: 'W Motors' },
  { name: 'WALD' },
  { name: 'WayRay' },
  { name: '万象汽车' },
  { name: '万达客车' },
  { name: '伟昊汽车' },
  { name: '五菱汽车' },
  { name: '五十铃' },
  { name: '现代' },
  { name: '雪佛兰' },
  { name: '雪铁龙' },
  { name: '西雅特' },
  { name: '新凯' },
  { name: '新吉奥' },
  { name: '新宝骏' },
  { name: '新特汽车' },
  { name: '新龙马汽车' },
  { name: '小米' },
  { name: '小猬汽车' },
  { name: '小虎' },
  { name: '小跑车' },
  { name: '小鹏' },
  { name: '小鹏汇天' },
  { name: '星程耀' },
  { name: '星海狮' },
  { name: '享界' },
  { name: '星途' },
  { name: '鑫源汽车' },
  { name: '寻星' },
  { name: 'XEV' },

  // Y 组（部分已在 V 组出现，这里补充）
  { name: 'YAMAHA' },
  { name: '野马汽车' },
  { name: '野马新能源' },
  { name: '一汽' },           // 已在 V 组
  { name: '一汽凌河' },       // 已在 V 组
  { name: '依维柯' },         // 已在 V 组
  { name: '英菲尼迪' },       // 已在 V 组
  { name: '英力士掷弹兵' },   // 已在 V 组
  { name: '永源' },           // 已在 V 组
  { name: '游侠' },           // 已在 V 组
  { name: '驭胜' },           // 已在 V 组
  { name: '云度' },           // 已在 V 组
  { name: '宇通客车' },       // 已在 V 组
  { name: '宇通房车' },       // 已在 V 组
  { name: '远程' },           // 已在 V 组
  { name: '远航汽车' },       // 已在 V 组
  { name: '越界' },           // 已在 V 组
  { name: '悠跑科技' },       // 已在 V 组
  { name: '悠宝利' },         // 已在 V 组
  { name: '仰望' },
  { name: '翼刻' },           // 已在 V 组
  { name: '运良汽车' },       // 已在 V 组
  { name: '予风汽车' },       // 已在 V 组
  { name: '烨' },             // 已在 V 组
  { name: 'firefly萤火虫' },  // 已在 V 组

  // Z 组
  { name: '中国重汽VGV' },
  { name: '众泰' },
  { name: '中兴' },
  { name: '知豆' },
  { name: '智己' },
  { name: '智点' },
  { name: '中车' },
  { name: '中集' },
  { name: '中华' },
  { name: '中欧' },
  { name: '中顺' },
  { name: '中泰' },
  { name: '中怡' },
  { name: '中植' },
  { name: '中置' },
  { name: '紫驰' },
  { name: '紫菱' },
  { name: '紫星' },
  { name: '纵横' },
  { name: 'Zenvo' },
  { name: '之诺' },
  { name: '正道汽车' },
  { name: '自游家' },
  { name: '智行盒子' },
  { name: '智界' },
  { name: '尊界' },
  { name: '追觅' },
  { name: '中意房车' },
  { name: '中通客车' },
  { name: '奕境' },
  { name: '亚特房车' },
];

// 生成最终品牌数组，自动生成 id 并计算首字母
export const carBrands = rawBrandsWithId.map(b => ({
  ...b,
  firstLetter: getFirstLetter(b.name), // 需要定义 getFirstLetter
  logoUrl: `/images/car_logos/${b.id}.png`,
}));